---
openapi: 3.0.0
info:
  title: Twitch Helix API
  description: The Twitch API is a RESTful API that lets developers build creative integrations for the broader Twitch community. THIS DOCUMENTATION IS NEITHER MAINTAINED BY OR AFFILIATED WITH TWITCH
  termsOfService: https://www.twitch.tv/p/en/legal/developer-agreement/
  contact:
    name: TwitchDev
    url: https://dev.twitch.tv/support/
    email: developers@twitch.tv
  version: Helix
servers:
- url: https://api.twitch.tv/helix
  description: Production API
paths:
  /channels/commercial:
    post:
      tags:
      - Ads
      summary: Start Commercial
      description: Starts a commercial on the specified channel.
      security:
      - oauth:
        - channel:edit:commercial
  /analytics/extensions:
    get:
      tags:
      - Analytics
      summary: Get Extension Analytics
      description: Gets an analytics report for one or more extensions.
      security:
      - oauth:
        - analytics:read:extensions
  /analytics/games:
    get:
      tags:
      - Analytics
      summary: Get Game Analytics
      description: Gets an analytics report for one or more games.
      security:
      - oauth:
        - analytics:read:games
  /bits/leaderboard:
    get:
      tags:
      - Bits
      summary: Get Bits Leaderboard
      description: Gets the Bits leaderboard for the authenticated broadcaster.
      security:
      - oauth:
        - bits:read
  /bits/cheermotes:
    get:
      tags:
      - Bits
      summary: Get Cheermotes
      description: Gets a list of Cheermotes that users can use to cheer Bits.
      security:
      - oauth: []
  /extensions/transactions:
    get:
      tags:
      - Bits
      summary: Get Extension Transactions
      description: Gets an extension’s list of transactions.
      security:
      - oauth: []
  /channels:
    get:
      tags:
      - Channels
      summary: Get Channel Information
      description: Gets information about one or more channels.
      security:
      - oauth: []
    patch:
      tags:
      - Channels
      summary: Modify Channel Information
      description: Updates a channel’s properties.
      security:
      - oauth:
        - channel:manage:broadcast
  /channels/editors:
    get:
      tags:
      - Channels
      summary: Get Channel Editors
      description: Gets the broadcaster’s list editors.
      security:
      - oauth:
        - channel:read:editors
  /channels/followed:
    get:
      tags:
      - Channels
      summary: Get Followed Channels
      description: Gets a list of broadcasters that the specified user follows. You can also use this endpoint to see whether a user follows a specific broadcaster.
      security:
      - oauth:
        - user:read:follows
  /channels/followers:
    get:
      tags:
      - Channels
      summary: Get Channel Followers
      description: Gets a list of users that follow the specified broadcaster. You can also use this endpoint to see whether a specific user follows the broadcaster.
      security:
      - oauth:
        - moderator:read:followers
  /channel_points/custom_rewards:
    get:
      tags:
      - Channel Points
      summary: Get Custom Reward
      description: Gets a list of custom rewards that the specified broadcaster created.
      security:
      - oauth:
        - channel:read:redemptions
    post:
      tags:
      - Channel Points
      summary: Create Custom Rewards
      description: Creates a Custom Reward in the broadcaster’s channel.
      security:
      - oauth:
        - channel:manage:redemptions
    delete:
      tags:
      - Channel Points
      summary: Delete Custom Reward
      description: Deletes a custom reward that the broadcaster created.
      security:
      - oauth:
        - channel:manage:redemptions
    patch:
      tags:
      - Channel Points
      summary: Update Custom Reward
      description: Updates a custom reward.
      security:
      - oauth:
        - channel:manage:redemptions
  /channel_points/custom_rewards/redemptions:
    get:
      tags:
      - Channel Points
      summary: Get Custom Reward Redemption
      description: Gets a list of redemptions for a custom reward.
      security:
      - oauth:
        - channel:read:redemptions
    patch:
      tags:
      - Channel Points
      summary: Update Redemption Status
      description: Updates a redemption’s status.
      security:
      - oauth:
        - channel:manage:redemptions
  /charity/campaigns:
    get:
      tags:
      - Charity
      summary: Get Charity Campaign
      description: Gets information about the broadcaster’s active charity campaign.
      security:
      - oauth:
        - channel:read:charity
  /charity/donations:
    get:
      tags:
      - Charity
      summary: Get Charity Campaign Donations
      description: Gets the list of donations that users have made to the broadcaster’s active charity campaign.
      security:
      - oauth: []
  /chat/chatters:
    get:
      tags:
      - Chat
      summary: Get Chatters
      description: Gets the list of users that are connected to the broadcaster’s chat session.
      security:
      - oauth:
        - moderator:read:chatters
  /chat/emotes:
    get:
      tags:
      - Chat
      summary: Get Channel Emotes
      description: Gets the broadcaster’s list of custom emotes.
      security:
      - oauth: []
  /chat/emotes/global:
    get:
      tags:
      - Chat
      summary: Get Global Emotes
      description: Gets all global emotes.
      security:
      - oauth: []
  /chat/emotes/set:
    get:
      tags:
      - Chat
      summary: Get Emote Sets
      description: Gets emotes for one or more specified emote sets.
      security:
      - oauth: []
  /chat/badges:
    get:
      tags:
      - Chat
      summary: Get Channel Chat Badges
      description: Gets the broadcaster’s list of custom chat badges.
      security:
      - oauth: []
  /chat/badges/global:
    get:
      tags:
      - Chat
      summary: Get Global Chat Badges
      description: Gets Twitch’s list of chat badges.
      security:
      - oauth: []
  /chat/settings:
    get:
      tags:
      - Chat
      summary: Get Chat Settings
      description: Gets the broadcaster’s chat settings.
      security:
      - oauth:
        - moderator:read:chat_settings
    patch:
      tags:
      - Chat
      summary: Update Chat Settings
      description: Updates the broadcaster’s chat settings.
      security:
      - oauth:
        - moderator:manage:chat_settings
  /chat/announcements:
    post:
      tags:
      - Chat
      summary: Send Chat Announcement
      description: Sends an announcement to the broadcaster’s chat room.
      security:
      - oauth:
        - moderator:manage:announcements
  /chat/shoutouts:
    post:
      tags:
      - Chat
      summary: Send a Shoutout
      description: Sends a Shoutout to the specified broadcaster.
      security:
      - oauth:
        - moderator:manage:shoutouts
  /chat/color:
    get:
      tags:
      - Chat
      summary: Get User Chat Color
      description: Gets the color used for the user’s name in chat.
      security:
      - oauth: []
    put:
      tags:
      - Chat
      summary: Update User Chat Color
      description: Updates the color used for the user’s name in chat.
      security:
      - oauth:
        - user:manage:chat_color
  /clips:
    get:
      tags:
      - Clips
      summary: Get Clips
      description: Gets one or more video clips.
      security:
      - oauth: []
    post:
      tags:
      - Clips
      summary: Create Clip
      description: Creates a clip from the broadcaster’s stream.
      security:
      - oauth:
        - clips:edit
  /content_classification_labels:
    get:
      tags:
      - CCLs
      summary: Get Content Classification Labels
      description: Gets information about Twitch content classification labels.
      security:
      - oauth: []
  /entitlements/drops:
    get:
      tags:
      - Entitlements
      summary: Get Drops Entitlements
      description: "Gets an organization’s list of entitlements that have been granted to a game, a user, or both."
      security:
      - oauth: []
    patch:
      tags:
      - Entitlements
      summary: Update Drops Entitlements
      description: Updates the Drop entitlement’s fulfillment status.
      security:
      - oauth: []
  /extensions/configurations:
    get:
      tags:
      - Extensions
      summary: Get Extension Configuration Segment
      description: Gets the specified configuration segment from the specified extension.
      security:
      - oauth: []
    put:
      tags:
      - Extensions
      summary: Set Extension Configuration Segment
      description: Updates a configuration segment.
      security:
      - oauth: []
  /extensions/required_configuration:
    put:
      tags:
      - Extensions
      summary: Set Extension Required Configuration
      description: Updates the extension’s required_configuration string.
      security:
      - oauth: []
  /extensions/pubsub:
    post:
      tags:
      - Extensions
      summary: Send Extension PubSub Message
      description: Sends a message to one or more viewers.
      security:
      - oauth: []
  /extensions/live:
    get:
      tags:
      - Extensions
      summary: Get Extension Live Channels
      description: Gets a list of broadcasters that are streaming live and have installed or activated the extension.
      security:
      - oauth: []
  /extensions/jwt/secrets:
    get:
      tags:
      - Extensions
      summary: Get Extension Secrets
      description: Gets an extension’s list of shared secrets.
      security:
      - oauth: []
    post:
      tags:
      - Extensions
      summary: Create Extension Secret
      description: Creates a shared secret used to sign and verify JWT tokens.
      security:
      - oauth: []
  /extensions/chat:
    post:
      tags:
      - Extensions
      summary: Send Extension Chat Message
      description: Sends a message to the specified broadcaster’s chat room.
      security:
      - oauth: []
  /extensions:
    get:
      tags:
      - Extensions
      summary: Get Extensions
      description: Gets information about an extension.
      security:
      - oauth: []
  /extensions/released:
    get:
      tags:
      - Extensions
      summary: Get Released Extensions
      description: Gets information about a released extension.
      security:
      - oauth: []
  /bits/extensions:
    get:
      tags:
      - Extensions
      summary: Get Extension Bits Products
      description: Gets the list of Bits products that belongs to the extension.
      security:
      - oauth: []
    put:
      tags:
      - Extensions
      summary: Update Extension Bits Product
      description: Adds or updates a Bits product that the extension created.
      security:
      - oauth: []
  /eventsub/subscriptions:
    get:
      tags:
      - EventSub
      summary: Get EventSub Subscriptions
      description: Gets a list of EventSub subscriptions that the client in the access token created.
      security:
      - oauth: []
    post:
      tags:
      - EventSub
      summary: Create EventSub Subscription
      description: Creates an EventSub subscription.
      security:
      - oauth: []
    delete:
      tags:
      - EventSub
      summary: Delete EventSub Subscription
      description: Deletes an EventSub subscription.
      security:
      - oauth: []
  /games/top:
    get:
      tags:
      - Games
      summary: Get Top Games
      description: Gets information about all broadcasts on Twitch.
      security:
      - oauth: []
  /games:
    get:
      tags:
      - Games
      summary: Get Games
      description: Gets information about specified games.
      security:
      - oauth: []
  /goals:
    get:
      tags:
      - Goals
      summary: Get Creator Goals
      description: Gets the broadcaster’s list of active goals.
      security:
      - oauth:
        - channel:read:goals
  /guest_star/channel_settings:
    get:
      tags:
      - Guest Star
      summary: Get Channel Guest Star Settings
      description: BETA Gets the channel settings for configuration of the Guest Star feature for a particular host.
      security:
      - oauth:
        - channel:read:guest_star
        - moderator:read:guest_star
    put:
      tags:
      - Guest Star
      summary: Update Channel Guest Star Settings
      description: BETA Mutates the channel settings for configuration of the Guest Star feature for a particular host.
      security:
      - oauth:
        - channel:manage:guest_star
  /guest_star/session:
    get:
      tags:
      - Guest Star
      summary: Get Guest Star Session
      description: BETA Gets information about an ongoing Guest Star session for a particular channel.
      security:
      - oauth:
        - channel:read:guest_star
        - moderator:read:guest_star
    post:
      tags:
      - Guest Star
      summary: Create Guest Star Session
      description: BETA Programmatically creates a Guest Star session on behalf of the broadcaster.
      security:
      - oauth:
        - channel:manage:guest_star
    delete:
      tags:
      - Guest Star
      summary: End Guest Star Session
      description: BETA Programmatically ends a Guest Star session on behalf of the broadcaster.
      security:
      - oauth:
        - channel:manage:guest_star
  /guest_star/invites:
    get:
      tags:
      - Guest Star
      summary: Get Guest Star Invites
      description: BETA Provides the caller with a list of pending invites to a Guest Star session.
      security:
      - oauth:
        - channel:read:guest_star
        - moderator:read:guest_star
    post:
      tags:
      - Guest Star
      summary: Send Guest Star Invite
      description: BETA Sends an invite to a specified guest on behalf of the broadcaster for a Guest Star session in progress.
      security:
      - oauth:
        - channel:manage:guest_star
        - moderator:manage:guest_star
    delete:
      tags:
      - Guest Star
      summary: Delete Guest Star Invite
      description: BETA Revokes a previously sent invite for a Guest Star session.
      security:
      - oauth:
        - channel:manage:guest_star
        - moderator:manage:guest_star
  /guest_star/slot:
    post:
      tags:
      - Guest Star
      summary: Assign Guest Star Slot
      description: BETA Allows a previously invited user to be assigned a slot within the active Guest Star session.
      security:
      - oauth:
        - channel:manage:guest_star
        - moderator:manage:guest_star
    delete:
      tags:
      - Guest Star
      summary: Delete Guest Star Slot
      description: BETA Allows a caller to remove a slot assignment from a user participating in an active Guest Star session.
      security:
      - oauth:
        - channel:manage:guest_star
        - moderator:manage:guest_star
    patch:
      tags:
      - Guest Star
      summary: Update Guest Star Slot
      description: BETA Allows a user to update the assigned slot for a particular user within the active Guest Star session.
      security:
      - oauth:
        - channel:manage:guest_star
        - moderator:manage:guest_star
  /guest_star/slot_settings:
    patch:
      tags:
      - Guest Star
      summary: Update Guest Star Slot Settings
      description: BETA Allows a user to update slot settings for a particular guest within a Guest Star session.
      security:
      - oauth:
        - channel:manage:guest_star
        - moderator:manage:guest_star
  /hypetrain/events:
    get:
      tags:
      - Hype Train
      summary: Get Hype Train Events
      description: Gets information about the broadcaster’s current or most recent Hype Train event.
      security:
      - oauth:
        - channel:read:hype_train
  /moderation/enforcements/status:
    post:
      tags:
      - Moderation
      summary: Check AutoMod Status
      description: Checks whether AutoMod would flag the specified message for review.
      security:
      - oauth:
        - moderation:read
  /moderation/automod/message:
    post:
      tags:
      - Moderation
      summary: Manage Held AutoMod Messages
      description: Allow or deny the message that AutoMod flagged for review.
      security:
      - oauth:
        - moderator:manage:automod
  /moderation/automod/settings:
    get:
      tags:
      - Moderation
      summary: Get AutoMod Settings
      description: Gets the broadcaster’s AutoMod settings.
      security:
      - oauth:
        - moderator:read:automod_settings
    put:
      tags:
      - Moderation
      summary: Update AutoMod Settings
      description: Updates the broadcaster’s AutoMod settings.
      security:
      - oauth:
        - moderator:manage:automod_settings
  /moderation/banned:
    get:
      tags:
      - Moderation
      summary: Get Banned Users
      description: Gets all users that the broadcaster banned or put in a timeout.
      security:
      - oauth:
        - moderation:read
  /moderation/bans:
    post:
      tags:
      - Moderation
      summary: Ban User
      description: Bans a user from participating in a broadcaster’s chat room or puts them in a timeout.
      security:
      - oauth:
        - moderator:manage:banned_users
    delete:
      tags:
      - Moderation
      summary: Unban User
      description: Removes the ban or timeout that was placed on the specified user.
      security:
      - oauth:
        - moderator:manage:banned_users
  /moderation/blocked_terms:
    get:
      tags:
      - Moderation
      summary: Get Blocked Terms
      description: "Gets the broadcaster’s list of non-private, blocked words or phrases."
      security:
      - oauth:
        - moderator:read:blocked_terms
    post:
      tags:
      - Moderation
      summary: Add Blocked Term
      description: Adds a word or phrase to the broadcaster’s list of blocked terms.
      security:
      - oauth:
        - moderator:manage:blocked_terms
    delete:
      tags:
      - Moderation
      summary: Remove Blocked Term
      description: Removes the word or phrase from the broadcaster’s list of blocked terms.
      security:
      - oauth:
        - moderator:manage:blocked_terms
  /moderation/chat:
    delete:
      tags:
      - Moderation
      summary: Delete Chat Messages
      description: Removes a single chat message or all chat messages from the broadcaster’s chat room.
      security:
      - oauth:
        - moderator:manage:chat_messages
  /moderation/moderators:
    get:
      tags:
      - Moderation
      summary: Get Moderators
      description: Gets all users allowed to moderate the broadcaster’s chat room.
      security:
      - oauth:
        - moderation:read
    post:
      tags:
      - Moderation
      summary: Add Channel Moderator
      description: Adds a moderator to the broadcaster’s chat room.
      security:
      - oauth:
        - channel:manage:moderators
    delete:
      tags:
      - Moderation
      summary: Remove Channel Moderator
      description: Removes a moderator from the broadcaster’s chat room.
      security:
      - oauth:
        - channel:manage:moderators
  /channels/vips:
    get:
      tags:
      - Moderation
      summary: Get VIPs
      description: Gets a list of the broadcaster’s VIPs.
      security:
      - oauth:
        - channel:read:vips
        - channel:manage:vips
    post:
      tags:
      - Moderation
      summary: Add Channel VIP
      description: Adds the specified user as a VIP in the broadcaster’s channel.
      security:
      - oauth:
        - channel:manage:vips
    delete:
      tags:
      - Moderation
      summary: Remove Channel VIP
      description: Removes the specified user as a VIP in the broadcaster’s channel.
      security:
      - oauth:
        - channel:manage:vips
  /moderation/shield_mode:
    get:
      tags:
      - Moderation
      summary: Get Shield Mode Status
      description: Gets the broadcaster’s Shield Mode activation status.
      security:
      - oauth:
        - moderator:read:shield_mode
    put:
      tags:
      - Moderation
      summary: Update Shield Mode Status
      description: Activates or deactivates the broadcaster’s Shield Mode.
      security:
      - oauth:
        - moderator:manage:shield_mode
  /polls:
    get:
      tags:
      - Polls
      summary: Get Polls
      description: Gets a list of polls that the broadcaster created.
      security:
      - oauth:
        - channel:read:polls
    post:
      tags:
      - Polls
      summary: Create Poll
      description: Creates a poll that viewers in the broadcaster’s channel can vote on.
      security:
      - oauth:
        - channel:manage:polls
    patch:
      tags:
      - Polls
      summary: End Poll
      description: End an active poll.
      security:
      - oauth:
        - channel:manage:polls
  /predictions:
    get:
      tags:
      - Predictions
      summary: Get Predictions
      description: Gets a list of Channel Points Predictions that the broadcaster created.
      security:
      - oauth:
        - channel:read:predictions
    post:
      tags:
      - Predictions
      summary: Create Prediction
      description: Create a Channel Points Prediction.
      security:
      - oauth:
        - channel:manage:predictions
    patch:
      tags:
      - Predictions
      summary: End Prediction
      description: "Locks, resolves, or cancels a Channel Points Prediction."
      security:
      - oauth:
        - channel:manage:predictions
  /raids:
    post:
      tags:
      - Raids
      summary: Start a raid
      description: Raid another channel by sending the broadcaster’s viewers to the targeted channel.
      security:
      - oauth:
        - channel:manage:raids
    delete:
      tags:
      - Raids
      summary: Cancel a raid
      description: Cancel a pending raid.
      security:
      - oauth:
        - channel:manage:raids
  /schedule:
    get:
      tags:
      - Schedule
      summary: Get Channel Stream Schedule
      description: Gets the broadcaster’s streaming schedule.
      security:
      - oauth: []
  /schedule/icalendar:
    get:
      tags:
      - Schedule
      summary: Get Channel iCalendar
      description: Gets the broadcaster’s streaming schedule as an iCalendar.
      security:
      - oauth: []
  /schedule/settings:
    patch:
      tags:
      - Schedule
      summary: Update Channel Stream Schedule
      description: "Updates the broadcaster’s schedule settings, such as scheduling a vacation."
      security:
      - oauth:
        - channel:manage:schedule
  /schedule/segment:
    post:
      tags:
      - Schedule
      summary: Create Channel Stream Schedule Segment
      description: Adds a single or recurring broadcast to the broadcaster’s streaming schedule.
      security:
      - oauth:
        - channel:manage:schedule
    delete:
      tags:
      - Schedule
      summary: Delete Channel Stream Schedule Segment
      description: Deletes a broadcast from the broadcaster’s streaming schedule.
      security:
      - oauth:
        - channel:manage:schedule
    patch:
      tags:
      - Schedule
      summary: Update Channel Stream Schedule Segment
      description: Updates a scheduled broadcast segment.
      security:
      - oauth:
        - channel:manage:schedule
  /search/categories:
    get:
      tags:
      - Search
      summary: Search Categories
      description: Gets the games or categories that match the specified query.
      security:
      - oauth: []
  /search/channels:
    get:
      tags:
      - Search
      summary: Search Channels
      description: Gets the channels that match the specified query and have streamed content within the past 6 months.
      security:
      - oauth: []
  /streams/key:
    get:
      tags:
      - Streams
      summary: Get Stream Key
      description: Gets the channel’s stream key.
      security:
      - oauth:
        - channel:read:stream_key
  /streams:
    get:
      tags:
      - Streams
      summary: Get Streams
      description: Gets a list of all streams.
      security:
      - oauth: []
  /streams/followed:
    get:
      tags:
      - Streams
      summary: Get Followed Streams
      description: Gets the list of broadcasters that the user follows and that are streaming live.
      security:
      - oauth:
        - user:read:follows
  /streams/markers:
    get:
      tags:
      - Streams
      summary: Get Stream Markers
      description: Gets a list of markers from the user’s most recent stream or from the specified VOD/video.
      security:
      - oauth:
        - user:read:broadcast
    post:
      tags:
      - Streams
      summary: Create Stream Marker
      description: Adds a marker to a live stream.
      security:
      - oauth:
        - channel:manage:broadcast
  /subscriptions:
    get:
      tags:
      - Subscriptions
      summary: Get Broadcaster Subscriptions
      description: Gets a list of users that subscribe to the specified broadcaster.
      security:
      - oauth:
        - channel:read:subscriptions
  /subscriptions/user:
    get:
      tags:
      - Subscriptions
      summary: Check User Subscription
      description: Checks whether the user subscribes to the broadcaster’s channel.
      security:
      - oauth:
        - user:read:subscriptions
  /tags/streams:
    get:
      tags:
      - Tags
      summary: Get All Stream Tags
      description: Gets the list of all stream tags that Twitch defines. You can also filter the list by one or more tag IDs.
      security:
      - oauth: []
  /streams/tags:
    get:
      tags:
      - Tags
      summary: Get Stream Tags
      description: Gets the list of stream tags that the broadcaster or Twitch added to their channel.
      security:
      - oauth: []
  /teams/channel:
    get:
      tags:
      - Teams
      summary: Get Channel Teams
      description: Gets the list of Twitch teams that the broadcaster is a member of.
      security:
      - oauth: []
  /teams:
    get:
      tags:
      - Teams
      summary: Get Teams
      description: Gets information about the specified Twitch team.
      security:
      - oauth: []
  /users:
    get:
      tags:
      - Users
      summary: Get Users
      description: Gets information about one or more users.
      security:
      - oauth:
        - user:read:email
    put:
      tags:
      - Users
      summary: Update User
      description: Updates the user’s information.
      security:
      - oauth:
        - user:edit
  /users/follows:
    get:
      tags:
      - Users
      summary: Get Users Follows
      description: Gets information about users that are following other users.
      security:
      - oauth: []
  /users/blocks:
    get:
      tags:
      - Users
      summary: Get User Block List
      description: Gets the list of users that the broadcaster has blocked.
      security:
      - oauth:
        - user:read:blocked_users
    put:
      tags:
      - Users
      summary: Block User
      description: Blocks the specified user from interacting with or having contact with the broadcaster.
      security:
      - oauth:
        - user:manage:blocked_users
    delete:
      tags:
      - Users
      summary: Unblock User
      description: Removes the user from the broadcaster’s list of blocked users.
      security:
      - oauth:
        - user:manage:blocked_users
  /users/extensions/list:
    get:
      tags:
      - Users
      summary: Get User Extensions
      description: Gets a list of all extensions (both active and inactive) that the broadcaster has installed.
      security:
      - oauth:
        - user:read:broadcast
  /users/extensions:
    get:
      tags:
      - Users
      summary: Get User Active Extensions
      description: Gets the active extensions that the broadcaster has installed for each configuration.
      security:
      - oauth:
        - channel:manage:extensions
        - user:read:broadcast
    put:
      tags:
      - Users
      summary: Update User Extensions
      description: Updates an installed extension’s information.
      security:
      - oauth:
        - channel:manage:extensions
  /videos:
    get:
      tags:
      - Videos
      summary: Get Videos
      description: Gets information about one or more published videos.
      security:
      - oauth: []
    delete:
      tags:
      - Videos
      summary: Delete Videos
      description: Deletes one or more videos.
      security:
      - oauth:
        - channel:manage:videos
  /whispers:
    post:
      tags:
      - Whispers
      summary: Send Whisper
      description: Sends a whisper message to the specified user.
      security:
      - oauth:
        - user:manage:whispers
components:
  securitySchemes:
    oauth:
      type: oauth2
      description: "Twitch APIs use OAuth 2.0 access tokens to access resources. If you’re not already familiar with the specification, reading it may help you better understand how to get access tokens to use with the Twitch API."
      flows:
        implicit:
          authorizationUrl: https://id.twitch.tv/oauth2/authorize
          scopes:
            channel:edit:commercial: Run commercials on a channel.
            analytics:read:extensions: View analytics data for the Twitch Extensions owned by the authenticated account.
            analytics:read:games: View analytics data for the games owned by the authenticated account.
            bits:read: View Bits information for a channel.
            channel:manage:broadcast: "Manage a channel’s broadcast configuration, including updating channel configuration and managing stream markers and stream tags."
            channel:read:editors: View a list of users with the editor role for a channel.
            user:read:follows: View the list of channels a user follows.
            moderator:read:followers: Read the followers of a broadcaster.
            channel:manage:redemptions: Manage Channel Points custom rewards and their redemptions on a channel.
            channel:read:redemptions: View Channel Points custom rewards and their redemptions on a channel.
            channel:read:charity: Read charity campaign details and user donations on your channel.
            moderator:read:chatters: View the chatters in a broadcaster’s chat room.
            moderator:read:chat_settings: View a broadcaster’s chat room settings.
            moderator:manage:chat_settings: Manage a broadcaster’s chat room settings.
            moderator:manage:announcements: Send announcements in channels where you have the moderator role.
            moderator:manage:shoutouts: Manage a broadcaster’s shoutouts.
            user:manage:chat_color: Update the color used for the user’s name in chat.
            clips:edit: Manage Clips for a channel.
            channel:read:goals: View Creator Goals for a channel.
            channel:read:guest_star: Read Guest Star details for your channel.
            moderator:read:guest_star: Read Guest Star details for channels where you are a Guest Star moderator.
            channel:manage:guest_star: Manage Guest Star for your channel.
            moderator:manage:guest_star: Manage Guest Star for channels where you are a Guest Star moderator.
            channel:read:hype_train: View Hype Train information for a channel.
            moderation:read: "View a channel’s moderation data including Moderators, Bans, Timeouts, and Automod settings."
            moderator:manage:automod: Manage messages held for review by AutoMod in channels where you are a moderator.
            moderator:read:automod_settings: View a broadcaster’s AutoMod settings.
            moderator:manage:automod_settings: Manage a broadcaster’s AutoMod settings.
            moderator:manage:banned_users: Ban and unban users.
            moderator:read:blocked_terms: View a broadcaster’s list of blocked terms.
            moderator:manage:blocked_terms: Manage a broadcaster’s list of blocked terms.
            moderator:manage:chat_messages: Delete chat messages in channels where you have the moderator role
            channel:manage:moderators: Add or remove the moderator role from users in your channel.
            channel:read:vips: Read the list of VIPs in your channel.
            channel:manage:vips: Add or remove the VIP role from users in your channel.
            moderator:manage:shield_mode: Manage a broadcaster’s Shield Mode status.
            moderator:read:shield_mode: View a broadcaster’s Shield Mode status.
            channel:read:polls: View a channel’s polls.
            channel:manage:polls: Manage a channel’s polls.
            channel:read:predictions: View a channel’s Channel Points Predictions.
            channel:manage:predictions: Manage of channel’s Channel Points Predictions
            channel:manage:raids: Manage a channel raiding another channel.
            channel:manage:schedule: Manage a channel’s stream schedule.
            channel:read:stream_key: View an authorized user’s stream key.
            user:read:broadcast: "View a user’s broadcasting configuration, including Extension configurations."
            channel:read:subscriptions: View a list of all subscribers to a channel and check if a user is subscribed to a channel.
            user:read:subscriptions: View if an authorized user is subscribed to specific channels.
            user:read:email: View a user’s email address.
            user:edit: Manage a user object.
            user:read:blocked_users: View the block list of a user.
            user:manage:blocked_users: Manage the block list of a user.
            channel:manage:extensions: "Manage a channel’s Extension configuration, including activating Extensions."
            channel:manage:videos: "Manage a channel’s videos, including deleting videos."
            user:manage:whispers: "Read whispers that you send and receive, and send whispers on your behalf."
        clientCredentials:
          tokenUrl: https://id.twitch.tv/oauth2/token
          scopes: {}
        authorizationCode:
          authorizationUrl: https://id.twitch.tv/oauth2/authorize
          tokenUrl: https://id.twitch.tv/oauth2/token
          scopes:
            channel:edit:commercial: Run commercials on a channel.
            analytics:read:extensions: View analytics data for the Twitch Extensions owned by the authenticated account.
            analytics:read:games: View analytics data for the games owned by the authenticated account.
            bits:read: View Bits information for a channel.
            channel:manage:broadcast: "Manage a channel’s broadcast configuration, including updating channel configuration and managing stream markers and stream tags."
            channel:read:editors: View a list of users with the editor role for a channel.
            user:read:follows: View the list of channels a user follows.
            moderator:read:followers: Read the followers of a broadcaster.
            channel:manage:redemptions: Manage Channel Points custom rewards and their redemptions on a channel.
            channel:read:redemptions: View Channel Points custom rewards and their redemptions on a channel.
            channel:read:charity: Read charity campaign details and user donations on your channel.
            moderator:read:chatters: View the chatters in a broadcaster’s chat room.
            moderator:read:chat_settings: View a broadcaster’s chat room settings.
            moderator:manage:chat_settings: Manage a broadcaster’s chat room settings.
            moderator:manage:announcements: Send announcements in channels where you have the moderator role.
            moderator:manage:shoutouts: Manage a broadcaster’s shoutouts.
            user:manage:chat_color: Update the color used for the user’s name in chat.
            clips:edit: Manage Clips for a channel.
            channel:read:goals: View Creator Goals for a channel.
            channel:read:guest_star: Read Guest Star details for your channel.
            moderator:read:guest_star: Read Guest Star details for channels where you are a Guest Star moderator.
            channel:manage:guest_star: Manage Guest Star for your channel.
            moderator:manage:guest_star: Manage Guest Star for channels where you are a Guest Star moderator.
            channel:read:hype_train: View Hype Train information for a channel.
            moderation:read: "View a channel’s moderation data including Moderators, Bans, Timeouts, and Automod settings."
            moderator:manage:automod: Manage messages held for review by AutoMod in channels where you are a moderator.
            moderator:read:automod_settings: View a broadcaster’s AutoMod settings.
            moderator:manage:automod_settings: Manage a broadcaster’s AutoMod settings.
            moderator:manage:banned_users: Ban and unban users.
            moderator:read:blocked_terms: View a broadcaster’s list of blocked terms.
            moderator:manage:blocked_terms: Manage a broadcaster’s list of blocked terms.
            moderator:manage:chat_messages: Delete chat messages in channels where you have the moderator role
            channel:manage:moderators: Add or remove the moderator role from users in your channel.
            channel:read:vips: Read the list of VIPs in your channel.
            channel:manage:vips: Add or remove the VIP role from users in your channel.
            moderator:manage:shield_mode: Manage a broadcaster’s Shield Mode status.
            moderator:read:shield_mode: View a broadcaster’s Shield Mode status.
            channel:read:polls: View a channel’s polls.
            channel:manage:polls: Manage a channel’s polls.
            channel:read:predictions: View a channel’s Channel Points Predictions.
            channel:manage:predictions: Manage of channel’s Channel Points Predictions
            channel:manage:raids: Manage a channel raiding another channel.
            channel:manage:schedule: Manage a channel’s stream schedule.
            channel:read:stream_key: View an authorized user’s stream key.
            user:read:broadcast: "View a user’s broadcasting configuration, including Extension configurations."
            channel:read:subscriptions: View a list of all subscribers to a channel and check if a user is subscribed to a channel.
            user:read:subscriptions: View if an authorized user is subscribed to specific channels.
            user:read:email: View a user’s email address.
            user:edit: Manage a user object.
            user:read:blocked_users: View the block list of a user.
            user:manage:blocked_users: Manage the block list of a user.
            channel:manage:extensions: "Manage a channel’s Extension configuration, including activating Extensions."
            channel:manage:videos: "Manage a channel’s videos, including deleting videos."
            user:manage:whispers: "Read whispers that you send and receive, and send whispers on your behalf."
